site_name: PD2023
site_url: https://ubriquejazz.github.io
nav:
    - Elementos de las BDs: U101.md
    - Modelo E/R extendido: U201.md
    - M.relacional. Normalizacion: U202.md
    - Diseno fisico. Lenguaje SQL: U301.md
    - Consultas sencillas: U401.md
    - Clausulas avanzadas: U402.md
    - Insert/Update/Delete: U501.md
    - Transacciones. Bloqueos: U502.md
    - Introduccion al PL/SQL: U503.md
    - Eventos y Triggers: U504.md
    - Seguridad de datos: U601.md
    - Copias de seguridad: U602.md
    - Importar y exportar: U603.md
    - About: about.md
theme: readthedocs